
export PATH=$PATH:~/dotfiles/bin:~/dotfiles/hypr/bin:~/dotfiles/dwm/bin/:~/.cargo/bin

#--- sys ---
alias psa='busybox ps'
alias c='clear'
alias e='echo'
alias s='source'
alias kcat='kitty icat'
alias ff='fastfetch'
alias una='uname -a'
alias ifcnf='ifconfig'
alias p='sudo pacman'
alias psy='sudo pacman -Sy'
alias psyu='sudo pacman -Syu'
alias pi='sudo pacman -S'
alias psc='sudo pacman -Ss'
alias ipr='ip route'
alias ipa='ip addr'
alias ipl='ip link'
#-----------

#--- git ---
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch'
alias gba='git branch --all'
alias gbd='git branch --delete'
alias gbD='git branch --delete --force'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gc='git clone'
alias gcl='git clone --recursive'
alias gcam='git commit --all --message'
alias gd='git diff'
alias gcf='git config --list'
alias gf='git fetch'
alias ghh='git help'
alias glgg='git log --graph'
alias glg='git log --stat'
alias gm='git merge'
alias gl='git pull'
alias gpr='git pull --rebase'
alias gp='git push'
alias gpo='git push --set-upstream origin'
alias gra='git remote add'
alias grrm='git remote remove'
alias gstall='git stash --all'
alias gst='git status'
#-----------

#--- docker ---
alias dpa='docker ps -a'
alias dp='docker ps'
alias dia='docker images -a'
alias di='docker images'
alias dcrm='docker container rm'
alias dirm='docker image rm'
alias dr='docker run'
alias ds='docker start'
alias dst='docker stop'
#--------------
